name: CI Workflow for Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade setuptools wheel
          # Pastikan install requirements dari MLProject biar versi mlflow sama
          pip install mlflow==2.14.1 dagshub scikit-learn pandas numpy matplotlib seaborn

      # 1. TRAIN MODEL
      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/farurin/Eksperimen_SML_Luthfiyana.mlflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # 2. LOGIN DOCKER HUB
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. BUILD & PUSH DOCKER IMAGE
      - name: Build and Push Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/farurin/Eksperimen_SML_Luthfiyana.mlflow
        run: |
          # Ambil Run ID langsung dari DagsHub menggunakan Python
          RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('$MLFLOW_TRACKING_URI'); runs = mlflow.search_runs(experiment_names=['Spam Filter Experiments'], order_by=['start_time DESC'], max_results=1); print(runs.iloc[0].run_id)")

          echo "Detected Run ID from DagsHub: $RUN_ID"

          # Nama Image
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/spam-classifier:latest"

          # Build Docker Image
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n "$IMAGE_NAME"

          # Push ke Docker Hub
          docker push "$IMAGE_NAME"
